### PR TITLE
OmicsIntegrator 2.2 (1/4) -- Fixes & Tests

### PR DESCRIPTION
**Pull request by zfrenchee**
Goals for this PR: (Requirements for OmicsIntegrator release 2.2.0): 
- [x] move from `os.path` to `pathlib`
- [x] replace all soon-to-be-deprecated fuzzy `.loc`s with `.reindex`s (#73)
(decided against) ~~move to pickled interactome files~~
- [x] change `gamma` to log-scale ([comment](https://github.com/fraenkel-lab/OmicsIntegrator2/pull/75#issuecomment-390752703), #57)
- [x] implement `_check_validity_of_instance` (#10)
(will leave this for later) ~~implement `augment_with_biological_process_terms`~~ 
(will leave this for later) ~~implement `augment_with_molecular_function_terms`~~ 
(decided not to implement) ~~implement `knockout` (#11)~~ 
- [x] create testing infrastructure
(will do this in a separate PR) ~~rebuild the docs~~

### CODE REVIEW

**Comment by iamjli** [comment]
@zfrenchee No, I do not.

**Comment by iamjli** [comment]
@zfrenchee Can we also change the `alpha` parameter to a log10 scale in this PR?

**Comment by zfrenchee** [comment]
@iamjli could you link to or re-explain the reasoning behind the formula which G modulates? Here's what the function looks like (for a hypothetical 1000-node interactome)

screen shot 2018-06-12 at 2 53 38 pm
screen shot 2018-06-12 at 2 53 51 pm

relative to the more straightforward (but perhaps less desirable) $$deg(A) * deg(B)$$

**Comment by zfrenchee** [comment]
@iamjli this PR is ready for an early review. The only meaningful changes are in graph.py, as usual.

**Comment by iamjli** [comment]
Re derivation of the node penalization scheme: the penalization is proportional (by constant G) to the probability of an edge existing between nodes a and b given deg(a) and deg(b).

**Pull request merged**
